version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/code
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=todo
      - DB_USER=admin
      - DB_PASSWORD=secret
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: mariadb/server:10.3
    environment:
      - MARIADB_DATABASE=todo
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=secret