global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.6.3:9100', '192.168.6.4:9100', '192.168.6.2:9100', '192.168.6.5:9100']

  - job_name: 'mariadb-exporter'
    static_configs:
      - targets: ['192.168.6.3:9104', '192.168.6.4:9104']

  - job_name: 'haproxy-exporter'
    static_configs:
      - targets: ['192.168.6.5:9101']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.6.5:8080', '192.168.6.2:8080', '192.168.6.3:8080', '192.168.6.4:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.6.5:9090']

rule_files:
  - "prometheus/mariadb_exp_rec.yml"