- hosts: control
  become: true
  tasks:
    - name: Restart Apache
      systemd:
        name: "apache2.service"
        state: restarted

    - name: Check Apache status
      systemd:
        name: "apache2.service"
        state: started

    - name: Start Nagios Service
      systemd:
        name: "nagios.service"
        state: started

    - name: Install Nagios plugins
      get_url:
        url: "https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz"
        dest: "/tmp/nagios-plugins.tar.gz"

    - name: Extract Nagios plugins
      unarchive:
        src: "/tmp/nagios-plugins.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Set up&Configure plugins
      become: yes
      become_user: root
      shell: |
        sudo apt-get install -y autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext
        cd /tmp/nagios-plugins-release-2.3.3/tools/
        sudo bash setup
        cd /tmp/nagios-plugins-release-2.3.3/
        sudo bash configure

    - name: Start Nagios Service
      systemd:
        name: "nagios.service"
        state: started
