version: "3.3"

services:
  db:
    image: mariadb/server:10.3
    env_file:
      - .env

  application:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "/code/wait-for-it.sh ${DB_HOST}:${DB_PORT} -t 45 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
